# Generated by Django 5.1.4 on 2025-01-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Đang hoạt động'), ('Maintenance', 'Bảo trì'), ('Closed', 'Đóng cửa')], default='Available', max_length=20)),
                ('available_slots', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
