# Generated by Django 5.1.4 on 2025-01-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_Mng', '0002_remove_court_available_slots_alter_court_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
