# Generated by Django 5.1.4 on 2024-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
