# Generated by Django 5.1.4 on 2025-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
