# Generated by Django 5.1.4 on 2025-01-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers_Mng', '0003_customer_address_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
